### ISSUE TITLE
Scripts to preprocess ACE2005 dataset

### ISSUE THREAD

**Issue by ynandwan** [wenhycs/NAACL2021-Event-Time-Extraction-and-Propagation-via-Graph-Attention-Networks#1]
Hi
Would it be possible for you to make the pre-processing scripts public? We have the ACE2005 dataset but do not know how to convert them to the desired json files.  

Thanks!

**Comment by wenhycs** [comment]
Hello, 
I got the preprocessing done partly from the primitive version of OneIE (http://blender.cs.illinois.edu/software/oneie/), which cannot be tracked now.
You can still use the current OneIE preprocessing (Although there might be some slight differences). Basically, you can use it to process sentences, and merge sentences (and corresponding knowledge elements) into documents.
