### ISSUE TITLE
Ask for help about input data

### ISSUE THREAD

**Issue by JiyaoWei** [wenhycs/NAACL2021-Event-Time-Extraction-and-Propagation-via-Graph-Attention-Networks#3]
Hello, I wander if it is convenient for you to give some examples to explain the structure of input data ("doc_ace.json", "doc_ace_entities.json", "extracted_temporal_relation.json")? Thank you very much!

**Comment by wenhycs** [comment]
Please see the email correspondence.

**Comment by littlelittleflower** [comment]
> Please see the email correspondence.

i also want to known the the structure of input data ("doc_ace.json", "doc_ace_entities.json", "extracted_temporal_relation.json")，Can you tell me via email (1028339752@qq.com)? Thank you very much!
